### ISSUE TITLE
Hitting 1000 file limite

### ISSUE THREAD

**Issue by markellul** [tallstreet/jaikuenginepatch#1]
Hi,

I just cloned the repo today, and tried to update GAE and I keep on hitting 1000 file limit.

In the app.yaml I added to the skip files:

|
|

So it should skip them... Below is the output from a python manage.py update. Is anyone else hitting this issue? 

Running on app-engine-patch 1.1beta1
Copying admin_media/img/admin/arrow-down.gif...
Copying admin_media/img/admin/arrow-up.gif...
Copying admin_media/img/admin/changelist-bg.gif...
Copying admin_media/img/admin/changelist-bg_rtl.gif...
Copying admin_media/img/admin/chooser-bg.gif...
Copying admin_media/img/admin/chooser_stacked-bg.gif...
Copying admin_media/img/admin/default-bg-reverse.gif...
Copying admin_media/img/admin/default-bg.gif...
Copying admin_media/img/admin/deleted-overlay.gif...
Copying admin_media/img/admin/icon-no.gif...
Copying admin_media/img/admin/icon-unknown.gif...
Copying admin_media/img/admin/icon-yes.gif...
Copying admin_media/img/admin/icon_addlink.gif...
Copying admin_media/img/admin/icon_alert.gif...
Copying admin_media/img/admin/icon_calendar.gif...
Copying admin_media/img/admin/icon_changelink.gif...
Copying admin_media/img/admin/icon_clock.gif...
Copying admin_media/img/admin/icon_deletelink.gif...
Copying admin_media/img/admin/icon_error.gif...
Copying admin_media/img/admin/icon_searchbox.png...
Copying admin_media/img/admin/icon_success.gif...
Copying admin_media/img/admin/inline-delete-8bit.png...
Copying admin_media/img/admin/inline-delete.png...
Copying admin_media/img/admin/inline-restore-8bit.png...
Copying admin_media/img/admin/inline-restore.png...
Copying admin_media/img/admin/inline-splitter-bg.gif...
Copying admin_media/img/admin/nav-bg-grabber.gif...
Copying admin_media/img/admin/nav-bg-reverse.gif...
Copying admin_media/img/admin/nav-bg.gif...
Copying admin_media/img/admin/selector-add.gif...
Copying admin_media/img/admin/selector-addall.gif...
Copying admin_media/img/admin/selector-remove.gif...
Copying admin_media/img/admin/selector-removeall.gif...
Copying admin_media/img/admin/selector-search.gif...
Copying admin_media/img/admin/selector_stacked-add.gif...
Copying admin_media/img/admin/selector_stacked-remove.gif...
Copying admin_media/img/admin/tool-left.gif...
Copying admin_media/img/admin/tool-left_over.gif...
Copying admin_media/img/admin/tool-right.gif...
Copying admin_media/img/admin/tool-right_over.gif...
Copying admin_media/img/admin/tooltag-add.gif...
Copying admin_media/img/admin/tooltag-add_over.gif...
Copying admin_media/img/admin/tooltag-arrowright.gif...
Copying admin_media/img/admin/tooltag-arrowright_over.gif...
Copying admin_media/img/gis/move_vertex_off.png...
Copying admin_media/img/gis/move_vertex_on.png...
Copying global/image/avatar_default_f.jpg...
Copying global/image/avatar_default_m.jpg...
Copying global/image/avatar_default_t.jpg...
Copying global/image/avatar_default_u.jpg...
Copying global/image/default/animal_1.mbm...
Copying global/image/default/animal_10.mbm...
Copying global/image/default/animal_10_f.jpg...
Copying global/image/default/animal_10_m.jpg...
Copying global/image/default/animal_10_t.jpg...
Copying global/image/default/animal_10_u.jpg...
Copying global/image/default/animal_11.mbm...
Copying global/image/default/animal_11_f.jpg...
Copying global/image/default/animal_11_m.jpg...
Copying global/image/default/animal_11_t.jpg...
Copying global/image/default/animal_11_u.jpg...
Copying global/image/default/animal_12.mbm...
Copying global/image/default/animal_12_f.jpg...
Copying global/image/default/animal_12_m.jpg...
Copying global/image/default/animal_12_t.jpg...
Copying global/image/default/animal_12_u.jpg...
Copying global/image/default/animal_13.mbm...
Copying global/image/default/animal_13_f.jpg...
Copying global/image/default/animal_13_m.jpg...
Copying global/image/default/animal_13_t.jpg...
Copying global/image/default/animal_13_u.jpg...
Copying global/image/default/animal_14.mbm...
Copying global/image/default/animal_14_f.jpg...
Copying global/image/default/animal_14_m.jpg...
Copying global/image/default/animal_14_t.jpg...
Copying global/image/default/animal_14_u.jpg...
Copying global/image/default/animal_15.mbm...
Copying global/image/default/animal_15_f.jpg...
Copying global/image/default/animal_15_m.jpg...
Copying global/image/default/animal_15_t.jpg...
Copying global/image/default/animal_15_u.jpg...
Copying global/image/default/animal_16.mbm...
Copying global/image/default/animal_16_f.jpg...
Copying global/image/default/animal_16_m.jpg...
Copying global/image/default/animal_16_t.jpg...
Copying global/image/default/animal_16_u.jpg...
Copying global/image/default/animal_17.mbm...
Copying global/image/default/animal_17_f.jpg...
Copying global/image/default/animal_17_m.jpg...
Copying global/image/default/animal_17_t.jpg...
Copying global/image/default/animal_17_u.jpg...
Copying global/image/default/animal_1_f.jpg...
Copying global/image/default/animal_1_m.jpg...
Copying global/image/default/animal_1_t.jpg...
Copying global/image/default/animal_1_u.jpg...
Copying global/image/default/animal_2.mbm...
Copying global/image/default/animal_2_f.jpg...
Copying global/image/default/animal_2_m.jpg...
Copying global/image/default/animal_2_t.jpg...
Copying global/image/default/animal_2_u.jpg...
Copying global/image/default/animal_3.mbm...
Copying global/image/default/animal_3_f.jpg...
Copying global/image/default/animal_3_m.jpg...
Copying global/image/default/animal_3_t.jpg...
Copying global/image/default/animal_3_u.jpg...
Copying global/image/default/animal_4.mbm...
Copying global/image/default/animal_4_f.jpg...
Copying global/image/default/animal_4_m.jpg...
Copying global/image/default/animal_4_t.jpg...
Copying global/image/default/animal_4_u.jpg...
Copying global/image/default/animal_5.mbm...
Copying global/image/default/animal_5_f.jpg...
Copying global/image/default/animal_5_m.jpg...
Copying global/image/default/animal_5_t.jpg...
Copying global/image/default/animal_5_u.jpg...
Copying global/image/default/animal_6.mbm...
Copying global/image/default/animal_6_f.jpg...
Copying global/image/default/animal_6_m.jpg...
Copying global/image/default/animal_6_t.jpg...
Copying global/image/default/animal_6_u.jpg...
Copying global/image/default/animal_7.mbm...
Copying global/image/default/animal_7_f.jpg...
Copying global/image/default/animal_7_m.jpg...
Copying global/image/default/animal_7_t.jpg...
Copying global/image/default/animal_7_u.jpg...
Copying global/image/default/animal_8.mbm...
Copying global/image/default/animal_8_f.jpg...
Copying global/image/default/animal_8_m.jpg...
Copying global/image/default/animal_8_t.jpg...
Copying global/image/default/animal_8_u.jpg...
Copying global/image/default/animal_9.mbm...
Copying global/image/default/animal_9_f.jpg...
Copying global/image/default/animal_9_m.jpg...
Copying global/image/default/animal_9_t.jpg...
Copying global/image/default/animal_9_u.jpg...
Copying global/image/default/creatembm.sh...
Copying global/images/add.gif...
Copying global/images/bg-content.gif...
Copying global/images/bg-content.png...
Copying global/images/bg-form-bubble.gif...
Copying global/images/bg_corner_b_l.gif...
Copying global/images/bg_corner_b_r.gif...
Copying global/images/bg_corner_t_l.gif...
Copying global/images/bg_corner_t_r.gif...
Copying global/images/bg_nav_bottom.gif...
Copying global/images/bg_nav_current_bottom.gif...
Copying global/images/bg_nav_current_left.gif...
Copying global/images/bg_nav_current_right.gif...
Copying global/images/bg_nav_hover_left.gif...
Copying global/images/bg_pipe.gif...
Copying global/images/bg_select.gif...
Copying global/images/bg_side_nav.gif...
Copying global/images/blank.gif...
Copying global/images/boilerplatebg.gif...
Copying global/images/calendar.gif...
Copying global/images/comment.gif...
Copying global/images/delete.gif...
Copying global/images/gray.gif...
Copying global/images/gray.png...
Copying global/images/green.gif...
Copying global/images/green.png...
Copying global/images/imagethrobber.gif...
Copying global/images/largebadgegray.gif...
Copying global/images/largebadgegreen.gif...
Copying global/images/largebadgeorange.gif...
Copying global/images/largebadgered.gif...
Copying global/images/location.gif...
Copying global/images/mediumbadgegray.gif...
Copying global/images/mediumbadgegreen.gif...
Copying global/images/mediumbadgeorange.gif...
Copying global/images/mediumbadgered.gif...
Copying global/images/near-by.gif...
Copying global/images/orange.gif...
Copying global/images/orange.png...
Copying global/images/pwstatus.gif...
Copying global/images/rcal.gif...
Copying global/images/red.gif...
Copying global/images/red.png...
Copying global/images/remove.gif...
Copying global/images/subnavsep.gif...
Copying global/images/throbber.gif...
Copying global/js/png-behavior.htc...
Copying global/static/favicon.ico...
Copying global/static/jaiku-file-description-web-service.doc...
Copying global/static/robots.txt...
Copying global/themes/trotz/bg-content-bottom.gif...
Copying global/themes/trotz/bg-content-bottom.png...
Copying global/themes/trotz/bg-content-top-g.gif...
Copying global/themes/trotz/bg-content-top-g.png...
Copying global/themes/trotz/bg-content-top.gif...
Copying global/themes/trotz/bg-content-top.png...
Copying global/themes/trotz/bg-content-w-bottom.gif...
Copying global/themes/trotz/bg-content-w-bottom.png...
Copying global/themes/trotz/bg-content-w-top-g.gif...
Copying global/themes/trotz/bg-content-w-top-g.png...
Copying global/themes/trotz/bg-content-w-top.gif...
Copying global/themes/trotz/bg-content-w-top.png...
Copying global/themes/trotz/bg-content-w.gif...
Copying global/themes/trotz/bg-content-w.png...
Copying global/themes/trotz/bg-content.gif...
Copying global/themes/trotz/bg-content.png...
Copying global/themes/trotz/bg-foot-step-b.gif...
Copying global/themes/trotz/bg-foot-step-dis-r.gif...
Copying global/themes/trotz/bg-foot-step-dis.gif...
Copying global/themes/trotz/bg-foot-step-r.gif...
Copying global/themes/trotz/bg-foot-step.gif...
Copying global/themes/trotz/bg-header.png...
Copying global/themes/trotz/bg-main.gif...
Copying global/themes/trotz/bg-sidebar-bottom.gif...
Copying global/themes/trotz/bg-sidebar-bottom.png...
Copying global/themes/trotz/bg-sidebar-top-g.gif...
Copying global/themes/trotz/bg-sidebar-top-g.png...
Copying global/themes/trotz/bg-sidebar-top.gif...
Copying global/themes/trotz/bg-sidebar-top.png...
Copying global/themes/trotz/bg-sidebar.gif...
Copying global/themes/trotz/bg-sidebar.png...
Copying global/themes/trotz/bg-step-1-done.gif...
Copying global/themes/trotz/bg-step-1-sel.gif...
Copying global/themes/trotz/bg-step-1-small.gif...
Copying global/themes/trotz/bg-step-1.gif...
Copying global/themes/trotz/bg-step-2-done.gif...
Copying global/themes/trotz/bg-step-2-sel.gif...
Copying global/themes/trotz/bg-step-2-small.gif...
Copying global/themes/trotz/bg-step-2.gif...
Copying global/themes/trotz/bg-step-3-done.gif...
Copying global/themes/trotz/bg-step-3-sel.gif...
Copying global/themes/trotz/bg-step-3-small.gif...
Copying global/themes/trotz/bg-step-3.gif...
Copying global/themes/trotz/bg-steps-line.gif...
Copying global/themes/trotz/favicon.ico...
Copying global/themes/trotz/icons/default.gif...
Copying global/themes/trotz/icons/feed-atom.gif...
Copying global/themes/trotz/icons/feed-blog.gif...
Copying global/themes/trotz/icons/feed-bookmark.gif...
Copying global/themes/trotz/icons/feed-bookwish.gif...
Copying global/themes/trotz/icons/feed-event.gif...
Copying global/themes/trotz/icons/feed-music.gif...
Copying global/themes/trotz/icons/feed-photo.gif...
Copying global/themes/trotz/icons/feed-places.gif...
Copying global/themes/trotz/icons/feed-video.gif...
Copying global/themes/trotz/icons/jaiku-bubble.gif...
Copying global/themes/trotz/icons/jaiku-comment.gif...
Copying global/themes/trotz/icons/jaiku-contact-added.gif...
Copying global/themes/trotz/icons/jaiku-couple.gif...
Copying global/themes/trotz/icons/jaiku-message.gif...
Copying global/themes/trotz/icons/jaiku-new-user.gif...
Copying global/themes/trotz/icons/jaiku-presence.gif...
Copying global/themes/trotz/icons/jaiku-sms.gif...
Copying global/themes/trotz/icons/web-airplain.gif...
Copying global/themes/trotz/icons/web-airport.gif...
Copying global/themes/trotz/icons/web-alarmclock.gif...
Copying global/themes/trotz/icons/web-baby-boy.gif...
Copying global/themes/trotz/icons/web-baby-girl.gif...
Copying global/themes/trotz/icons/web-balloons.gif...
Copying global/themes/trotz/icons/web-bandaid.gif...
Copying global/themes/trotz/icons/web-barrier.gif...
Copying global/themes/trotz/icons/web-basketball.gif...
Copying global/themes/trotz/icons/web-beer.gif...
Copying global/themes/trotz/icons/web-bike.gif...
Copying global/themes/trotz/icons/web-binoculars.gif...
Copying global/themes/trotz/icons/web-blading.gif...
Copying global/themes/trotz/icons/web-boiler.gif...
Copying global/themes/trotz/icons/web-bomb.gif...
Copying global/themes/trotz/icons/web-book.gif...
Copying global/themes/trotz/icons/web-bra.gif...
Copying global/themes/trotz/icons/web-bus.gif...
Copying global/themes/trotz/icons/web-camera.gif...
Copying global/themes/trotz/icons/web-car.gif...
Copying global/themes/trotz/icons/web-casette.gif...
Copying global/themes/trotz/icons/web-champaign.gif...
Copying global/themes/trotz/icons/web-cigarettes.gif...
Copying global/themes/trotz/icons/web-clean.gif...
Copying global/themes/trotz/icons/web-clock.gif...
Copying global/themes/trotz/icons/web-cloudy.gif...
Copying global/themes/trotz/icons/web-coffee.gif...
Copying global/themes/trotz/icons/web-computer.gif...
Copying global/themes/trotz/icons/web-computing.gif...
Copying global/themes/trotz/icons/web-cone.gif...
Copying global/themes/trotz/icons/web-disc.gif...
Copying global/themes/trotz/icons/web-driller.gif...
Copying global/themes/trotz/icons/web-eat.gif...
Copying global/themes/trotz/icons/web-event.gif...
Copying global/themes/trotz/icons/web-exclamationmark.gif...
Copying global/themes/trotz/icons/web-football.gif...
Copying global/themes/trotz/icons/web-footballshoe.gif...
Copying global/themes/trotz/icons/web-fork.gif...
Copying global/themes/trotz/icons/web-game.gif...
Copying global/themes/trotz/icons/web-gameboy.gif...
Copying global/themes/trotz/icons/web-grenade.gif...
Copying global/themes/trotz/icons/web-grumpy.gif...
Copying global/themes/trotz/icons/web-hand.gif...
Copying global/themes/trotz/icons/web-hanger.gif...
Copying global/themes/trotz/icons/web-happy.gif...
Copying global/themes/trotz/icons/web-hearingprotector.gif...
Copying global/themes/trotz/icons/web-home.gif...
Copying global/themes/trotz/icons/web-hurry.gif...
Copying global/themes/trotz/icons/web-icecream.gif...
Copying global/themes/trotz/icons/web-laptop.gif...
Copying global/themes/trotz/icons/web-lifejacket.gif...
Copying global/themes/trotz/icons/web-loudspeaker.gif...
Copying global/themes/trotz/icons/web-love.gif...
Copying global/themes/trotz/icons/web-luggage.gif...
Copying global/themes/trotz/icons/web-makeup.gif...
Copying global/themes/trotz/icons/web-megaphone.gif...
Copying global/themes/trotz/icons/web-metro.gif...
Copying global/themes/trotz/icons/web-microwave.gif...
Copying global/themes/trotz/icons/web-middlefinger.gif...
Copying global/themes/trotz/icons/web-morning.gif...
Copying global/themes/trotz/icons/web-movie.gif...
Copying global/themes/trotz/icons/web-notes.gif...
Copying global/themes/trotz/icons/web-picnic.gif...
Copying global/themes/trotz/icons/web-pils.gif...
Copying global/themes/trotz/icons/web-playshirt.gif...
Copying global/themes/trotz/icons/web-popcorn.gif...
Copying global/themes/trotz/icons/web-question.gif...
Copying global/themes/trotz/icons/web-rollator.gif...
Copying global/themes/trotz/icons/web-rollerblade.gif...
Copying global/themes/trotz/icons/web-salt.gif...
Copying global/themes/trotz/icons/web-scoop.gif...
Copying global/themes/trotz/icons/web-scull.gif...
Copying global/themes/trotz/icons/web-search.gif...
Copying global/themes/trotz/icons/web-shop.gif...
Copying global/themes/trotz/icons/web-shuttlecock.gif...
Copying global/themes/trotz/icons/web-sk8.gif...
Copying global/themes/trotz/icons/web-sleep.gif...
Copying global/themes/trotz/icons/web-snorkeling.gif...
Copying global/themes/trotz/icons/web-snowflake.gif...
Copying global/themes/trotz/icons/web-soda.gif...
Copying global/themes/trotz/icons/web-song.gif...
Copying global/themes/trotz/icons/web-speechbubble.gif...
Copying global/themes/trotz/icons/web-spray.gif...
Copying global/themes/trotz/icons/web-spraycan.gif...
Copying global/themes/trotz/icons/web-sticks.gif...
Copying global/themes/trotz/icons/web-storm.gif...
Copying global/themes/trotz/icons/web-straitjacket.gif...
Copying global/themes/trotz/icons/web-subway.gif...
Copying global/themes/trotz/icons/web-sun.gif...
Copying global/themes/trotz/icons/web-taxi.gif...
Copying global/themes/trotz/icons/web-technics.gif...
Copying global/themes/trotz/icons/web-theatre.gif...
Copying global/themes/trotz/icons/web-toaster.gif...
Copying global/themes/trotz/icons/web-toiletpaper.gif...
Copying global/themes/trotz/icons/web-train.gif...
Copying global/themes/trotz/icons/web-tram.gif...
Copying global/themes/trotz/icons/web-trashcan.gif...
Copying global/themes/trotz/icons/web-travel.gif...
Copying global/themes/trotz/icons/web-tv.gif...
Copying global/themes/trotz/icons/web-underware.gif...
Copying global/themes/trotz/icons/web-uzi.gif...
Copying global/themes/trotz/icons/web-videocamera.gif...
Copying global/themes/trotz/icons/web-videotape.gif...
Copying global/themes/trotz/icons/web-vinyl.gif...
Copying global/themes/trotz/icons/web-walk.gif...
Copying global/themes/trotz/icons/web-wallclock.gif...
Copying global/themes/trotz/icons/web-wheelchair.gif...
Copying global/themes/trotz/icons/web-wine.gif...
Copying global/themes/trotz/icons/web-zippo.gif...
Copying global/themes/trotz/join_now.jpg...
Copying global/themes/trotz/logo-big.gif...
Copying global/themes/trotz/logo-welcome.gif...
Copying global/themes/trotz/logo.png...
Copying global/themes/trotz/welcome-done.gif...
Combining admin_media/css/base.css...
  Running yuicompressor... 9353 bytes
Combining admin_media/css/changelists.css...
  Running yuicompressor... 3498 bytes
Combining admin_media/css/dashboard.css...
  Running yuicompressor... 228 bytes
Combining admin_media/css/forms.css...
  Running yuicompressor... 3918 bytes
Combining admin_media/css/ie.css...
  Running yuicompressor... 362 bytes
Combining admin_media/css/login.css...
  Running yuicompressor... 574 bytes
Combining admin_media/css/rtl.css...
  Running yuicompressor... 2154 bytes
Combining admin_media/css/widgets.css...
  Running yuicompressor... 7008 bytes
Combining admin_media/js/SelectBox.js...
  Running yuicompressor... 2094 bytes
Combining admin_media/js/SelectFilter2.js...
  Running yuicompressor... 3327 bytes
Combining admin_media/js/actions.js...
  Running yuicompressor... 407 bytes
Combining admin_media/js/admin/CollapsedFieldsets.js...
  Running yuicompressor... 1905 bytes
Combining admin_media/js/admin/DateTimeShortcuts.js...
  Running yuicompressor... 7110 bytes
Combining admin_media/js/admin/RelatedObjectLookups.js...
  Running yuicompressor... 1539 bytes
Combining admin_media/js/admin/ordering.js...
  Running yuicompressor... 1886 bytes
Combining admin_media/js/calendar.js...
  Running yuicompressor... 2427 bytes
Combining admin_media/js/core.js...
  Running yuicompressor... 3037 bytes
Combining admin_media/js/dateparse.js...
  Running yuicompressor... 3584 bytes
Combining admin_media/js/getElementsBySelector.js...
  Running yuicompressor... 1987 bytes
Combining admin_media/js/timeparse.js...
  Running yuicompressor... 1010 bytes
Combining admin_media/js/urlify.js...
  Running yuicompressor... 3984 bytes
Combining combined-en.js...
  Running yuicompressor... 33839 bytes
Combining combined-ltr.css...
  Running yuicompressor... 42278 bytes
Combining combined-rtl.css...
  Running yuicompressor... 42278 bytes
Combining ie.css...
  Running yuicompressor... 1867 bytes
Combining screen-ietrotz.css...
  Running yuicompressor... 430 bytes
Combining screentrotz.css...
  Running yuicompressor... 7710 bytes
Scanning files on local disk.
Scanned 500 files.
Scanned 1000 files.
Scanned 1500 files.
Initiating update.
Could not guess mimetype for _generated_media/1/global/image/default/animal_13.mbm.  Using application/octet-stream.
Could not guess mimetype for _generated_media/1/global/image/default/animal_14.mbm.  Using application/octet-stream.
Could not guess mimetype for _generated_media/1/global/image/default/animal_9.mbm.  Using application/octet-stream.
Could not guess mimetype for _generated_media/1/global/image/default/animal_12.mbm.  Using application/octet-stream.
Could not guess mimetype for _generated_media/1/global/js/png-behavior.htc.  Using application/octet-stream.
Could not guess mimetype for _generated_media/1/global/image/default/animal_4.mbm.  Using application/octet-stream.
Could not guess mimetype for _generated_media/1/global/image/default/animal_1.mbm.  Using application/octet-stream.
Could not guess mimetype for _generated_media/1/global/image/default/animal_17.mbm.  Using application/octet-stream.
Could not guess mimetype for _generated_media/1/global/image/default/animal_8.mbm.  Using application/octet-stream.
Could not guess mimetype for _generated_media/1/global/image/default/animal_7.mbm.  Using application/octet-stream.
Could not guess mimetype for _generated_media/1/global/image/default/animal_2.mbm.  Using application/octet-stream.
Could not guess mimetype for _generated_media/1/global/image/default/animal_16.mbm.  Using application/octet-stream.
Could not guess mimetype for _generated_media/1/global/image/default/animal_6.mbm.  Using application/octet-stream.
Could not guess mimetype for _generated_media/1/global/image/default/animal_5.mbm.  Using application/octet-stream.
Could not guess mimetype for _generated_media/1/global/image/default/animal_10.mbm.  Using application/octet-stream.
Could not guess mimetype for _generated_media/1/global/image/default/animal_3.mbm.  Using application/octet-stream.
Could not guess mimetype for _generated_media/1/global/image/default/animal_11.mbm.  Using application/octet-stream.
Could not guess mimetype for _generated_media/1/global/image/default/animal_15.mbm.  Using application/octet-stream.
Cloning 389 static files.
Cloned 100 files.
Cloned 200 files.
Cloned 300 files.
Cloning 699 application files.
Cloned 100 files.
Cloned 200 files.
Cloned 300 files.
Cloned 400 files.
Cloned 500 files.
Cloned 600 files.
Uploading 6 files.
ERROR:root:An unexpected error occurred. Aborting.
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/appcfg.py", line 1227, in DoUpload
    self.UploadFile(missing_file, file_handle)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/appcfg.py", line 1084, in UploadFile
    payload=file_handle.read())
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/appengine_rpc.py", line 344, in Send
    f = self.opener.open(req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/urllib2.py", line 380, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/urllib2.py", line 491, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/urllib2.py", line 418, in error
    return self._call_chain(_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/urllib2.py", line 353, in _call_chain
    result = func(_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/urllib2.py", line 499, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 400: Bad Request
Rolling back the update.
Error 400: --- begin server output ---
Max number of files and blobs is 1000.
--- end server output ---

**Comment by markellul** [comment]
I have created in essence a workaround:
- First run the python manage.py update. If will fail.
- Then zip up all the contents inside of the _generated_media folder (not the folder itself).
- Name the zip file media.zip and put it in the root folder of the project.
- Change the app.yaml entry where the media is to this *
  ***
  - url: /media/.*
    script: $PYTHON_LIB/google/appengine/ext/zipserve

**Comment by tallstreet** [comment]
i believe the limit has now been raised to 3000 so that should also resolve this issue.
